export type OrderStatus = 'new' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'canceled' | 'returned';

export interface Store {
  id: string;
  /** Immutable public identifier generated by Postgres. */
  storeCode: string;
  name: string;
  image: string;
  facebookPage: string;
  mobileNumber: string;
  businessGroupId: string;
  productCount: number;
  customerCount: number;
  orderCount: number;
  totalProfit: number;
  lastActivity: string;
}

export interface Product {
  id: string;
  storeId: string;
  name: string;
  description: string;
  images: string[];
  purchasePrice: number;
  sellingPrice: number;
  margin: number;
  sku: string;
  barcode: string;
  brand: string;
  provider: string;
  category: string;
  defaultSerial: string;
  colors: string[];
  sizes: string[];
  stock: number;
  minStock: number;
  status: 'active' | 'draft' | 'out_of_stock';
  addedAt: string;
  salesCount: number;
}

export interface Customer {
  id: string;
  /** Customers belong to one store; the same person in two stores is two rows. */
  storeId: string;
  /** Issued by the customer naming series. Empty on rows created before it. */
  code: string;
  name: string;
  phone: string;
  whatsapp: string;
  city: string;
  address: string;
  orderCount: number;
  totalSpent: number;
  lastPurchase: string;
  rating: number; // 1-5
  status: 'active' | 'inactive' | 'vip';
}

export interface OrderItem {
  productId: string;
  productName: string;
  quantity: number;
  price: number;
  image: string;
  /** Chosen from the product's `sizes` when it has any. Empty when it does not. */
  size?: string;
}

export interface Order {
  id: string;
  orderNumber: string;
  storeId: string;
  customerId: string;
  customerName: string;
  items: OrderItem[];
  subtotal: number;
  discount: number;
  deliveryFee: number;
  total: number;
  status: OrderStatus;
  notes: string;
  createdAt: string;
  deliveryDate?: string;
  agentId?: string;
  /** Delivery zone the order was composed against; drives the rep's commission. */
  zoneId?: string;
  /** The naming series the order number came from, e.g. `ORD-.YYYY.-.####`. */
  namingSeries?: string;
}

/**
 * How one kind of document is numbered — the Frappe model: a doctype offers a
 * list of series and defaults to one of them.
 *
 * A series is a pattern: `ORD-.YYYY.-.####` yields ORD-2026-0001. `.YYYY.`
 * `.YY.` `.MM.` `.DD.` are replaced when the document is created, and the run of
 * `#` is the counter, its length the zero-padding.
 */
export interface DocumentNaming {
  /** The table the documents live in: 'orders', 'customers', … */
  doctype: string;
  label: string;
  series: string[];
  defaultSeries: string;
  /** true counts per store, so every store's first document is number 1. */
  perStore: boolean;
  /** The store that owns this setting, or '' for the default every store starts from. */
  storeKey: string;
}

export interface NamingCounter {
  prefix: string;
  /** Store id, or '' for a doctype counted globally. */
  storeKey: string;
  current: number;
}

/** Why stock moved. 'sale' and 'initial' are written by the system, not chosen. */
export type StockKind = 'purchase' | 'sale' | 'return' | 'damage' | 'adjustment' | 'initial';

export interface StockEntry {
  id: string;
  productId: string;
  storeId: string;
  kind: StockKind;
  /** Signed delta: +5 received, -2 sold. */
  quantity: number;
  /** Stock immediately after this movement. */
  balance: number;
  note: string;
  orderId?: string;
  createdAt: string;
}

export type ZoneRegion = 'tripolitania' | 'cyrenaica' | 'fezzan';

/**
 * How a rep is paid for delivering into a zone. 'none' means the zone says
 * nothing and the rep's own flat commission applies.
 */
export type CommissionType = 'none' | 'fixed' | 'percent';

/** المدينة الكبرى — level 1, the parent every scope and area hangs off. */
export interface City {
  id: string;
  name: string;
  region: ZoneRegion;
  active: boolean;
}

/**
 * النطاق الجغرافي — level 2.
 *
 * Operational rather than administrative, and only meaningful under its city:
 * «غرب طرابلس» is not a name that travels.
 */
export interface ZoneScope {
  id: string;
  cityId: string;
  name: string;
}

/** البلدية — level 4. The official list, not something a store invents. */
export interface Municipality {
  id: string;
  name: string;
}

export interface DeliveryZone {
  id: string;
  /** Sequential, operator-facing zone number: '00', '01', … Assigned by Postgres. */
  code: string;
  name: string;
  region: ZoneRegion;
  areaKm2: number;
  fee: number;
  deliveryTimeDays: number;
  active: boolean;
  commissionType: CommissionType;
  /** A percentage of the delivery fee, or a flat amount — read per `commissionType`. */
  commissionValue: number;
  /**
   * Null for the shared default catalogue every store starts from. Set once a
   * store edits a zone: that store then works with its own copy, and `sourceId`
   * points at the default the copy replaced.
   */
  storeId?: string | null;
  sourceId?: string | null;
  /**
   * The three levels around this area.
   *
   * The `*Id` is the truth; the text beside it is a copy Postgres keeps in step,
   * so lists, filters, the tree and the export read a flat row without a join.
   * A row imported by name alone has the text and no link until it is matched.
   */
  cityId: string | null;
  city: string;
  scopeId: string | null;
  scope: string;
  municipalityId: string | null;
  municipality: string;
  /** Latin or historic name where one is known. */
  altName: string;
  lat: number | null;
  lon: number | null;
  /** The source holds a Latin name only; an Arabic one still has to be written. */
  needsTranslation: boolean;
  /** OpenStreetMap element this row came from, e.g. `OSM relation/14710700`. */
  source: string;
}

export interface Expense {
  id: string;
  title: string;
  type: 'ads' | 'shipping' | 'salary' | 'rent' | 'other';
  amount: number;
  date: string;
  storeId?: string;
}

export interface SalesRep {
  id: string;
  storeId: string;
  /** Issued by the rep naming series. Empty on rows created before it. */
  code: string;
  name: string;
  phone: string;
  whatsapp: string;
  /** Delivery zone names covered, matching DeliveryZone.name. Empty = all zones. */
  zones: string[];
  /** Flat amount per delivered order, used where the zone sets no commission. */
  commission: number;
  active: boolean;
  note: string;
  createdAt: string;
}

export type UserRole = 'admin' | 'user';

export interface Profile {
  id: string;
  email: string;
  displayName: string;
  role: UserRole;
  active: boolean;
  createdAt: string;
}

export interface StoreRole {
  id: string;
  storeId: string;
  name: string;
  description: string;
  rank: number;
  isSystem: boolean;
}

export interface DocTypeDefinition {
  name: string;
  label: string;
  module: string;
  isSystem: boolean;
  isActive: boolean;
  isSubmittable: boolean;
}

export interface StoreRolePermission {
  roleId: string;
  doctype: string;
  permLevel: number;
  canRead: boolean;
  canWrite: boolean;
  canCreate: boolean;
  canDelete: boolean;
  canSubmit: boolean;
  canCancel: boolean;
  canAmend: boolean;
  canReport: boolean;
  canExport: boolean;
  canImport: boolean;
  canSetUserPermissions: boolean;
  canShare: boolean;
  canPrint: boolean;
  canEmail: boolean;
}

export interface StoreAccessRequest {
  id: string;
  storeId: string;
  storeCode: string;
  storeName: string;
  requesterId: string;
  requesterName: string;
  requestedRole: string;
  status: 'pending' | 'approved' | 'rejected' | 'cancelled';
  canReview?: boolean;
  createdAt: string;
}
